### ISSUE TITLE
Emailing Teachers

### ISSUE THREAD

**Issue by Keenei** [MTM6330-F18/Final-BIETZ#6]
Emailing select teachers for a small statement on their respective courses:

Michael - Server-Side/Client-Side
Ruffino - UX Design
Hussein - CMS + Motion Graphics

**Comment by JazminEickmeier** [comment]
Michael - Server-Side/Client-Side

> _My name is Michael Eisenbraun and I am currently a part-time professor at Algonquin College for the Interactive Media and Design program. I teach Client-Side Web Development in Level 2 and Server-Side Web Development in Level 3._

>  

> _I am largely self-taught and constantly striving to learn more. The field of web design and development is ever-changing and if you don’t keep moving, you will fall behind. It is this realization that led me to start teaching at Algonquin College in January of 2016. I have a passion for learning and it fuels my desire to share what I know with others. It has become my new passion and my primary focus. I aim to be the best teacher I can, and it is my hope that my students will find the same spark of curiosity that changed my life all those years ago._

>  

> _Many students who join the IMD program, do so for the video and design. So they are often caught off guard by the amount of programming required. While I don’t expect students to have prior programming experience, I would like perspective students to know that programming is taught in IMD and that they don’t have afraid of it. Anyone can learn to program if they are willing to try._

**Comment by JazminEickmeier** [comment]
Rufino - UX Design



> _I'm Rufino R. Ansara - a graduate of Carleton and Algonquin's joint IMD program and Carleton's Master's of Applied Science: Human Computer Interaction (HCI). I'm currently working for the Government of Canada as an IT Analyst, but I  taught UX Design at Algonquin College in Winter 2018. I've also worked as a Software Developer in a small startup, and have had the opportunity to teach at Carleton University, specifically Introduction to Multimedia and Design (Fall 2016 and 2017), Design Studio I (Winter 2018) and 3D Computer Graphics (Winter 2018)._

> _Like many IMD students, I joined the program hoping to become a specialist in video editing and special effects - but I quickly learned programming was a big part of the field. I was originally afraid, but I eventually realized that the best aspect of being an IMD student was our versatility: we know how to design, we know how to program and thus, are often excellent at bridging those two worlds. This is a critical skill in the current job market.  That's something I encourage you to remember when you struggle with the  broad skill set required to excel in all the courses in the program: it will eventually pay off!_
